### ISSUE TITLE
Build failure in Ubuntu 14.04

### ISSUE THREAD

**Issue by phamhoanganhbk** [OpenAADL/ocarina-build#38]
Hi everyone,

I am a newbie of AADL and I am trying to install Ocarina following this step 
1. `git clone https://github.com/OpenAADL/ocarina-build.git`
2. `./build_ocarina.sh -s -u`
3. `./build_ocarina.sh -b`

I have tried to use GNAT 2015 and GNAT but there are same errors :
`anhph@anhph:~/ocarina-build$ ./build_ocarina.sh --scenario=fresh-install --prefix=$PWD/ocarina_install
OS:        Ubuntu 14.04.5 LTS x86_64
Compiler:  GNATMAKE 4.6
autoconf:  autoconf (GNU Autoconf) 2.69
automake:  automake (GNU automake) 1.14.1
[2019-01-17-13:22] Checkout the Ocarina sources                                                                                          [PASSED]
[2019-01-17-13:22] Fetching runtimes 'polyorb-hi-ada polyorb-hi-c aadlib'                                                                [PASSED]
[2019-01-17-13:22] Reconfiguring (Ocarina)                                                                                               [PASSED]
[2019-01-17-13:22] First configure (Ocarina)                                                                                             [PASSED]
[2019-01-17-13:22] Doing 'make' (Ocarina)[2019-01-17-13:22] Doing 'make' (Ocarina)                                                                                                [FAILED]
Making all in support
make[1]: Entering directory `/home/anhph/ocarina-build/ocarina/support'
make[1]: Nothing to be done for `all'.
make[1]: Leaving directory `/home/anhph/ocarina-build/ocarina/support'
Making all in tools
make[1]: Entering directory `/home/anhph/ocarina-build/ocarina/tools'
make[2]: Entering directory `/home/anhph/ocarina-build/ocarina/tools'
make[2]: Nothing to be done for `all-am'.
make[2]: Leaving directory `/home/anhph/ocarina-build/ocarina/tools'
make[1]: Leaving directory `/home/anhph/ocarina-build/ocarina/tools'
Making all in projects
make[1]: Entering directory `/home/anhph/ocarina-build/ocarina/projects'
Makefile:608: target `gnatcheck' doesn't match the target pattern
Makefile:614: target `gnatmetric' doesn't match the target pattern
touch ../src/core/objects-stamp
touch ../src/config/objects-stamp
touch ../src/frontends/objects-stamp
touch ../src/backends/objects-stamp
touch ../src/transfo/objects-stamp
touch ../src/main/objects-stamp
touch ../src/python/objects-stamp
touch ../src/core/libs-stamp
touch ../src/frontends/libs-stamp
touch ../src/backends/libs-stamp
touch ../src/transfo/libs-stamp
touch ../src/config/libs-stamp
touch ../src/main/libs-stamp
touch ../src/python/libs-stamp
Creating directory: ../src/core/objects
mkdir -p ../src/core/objects
Creating directory: ../src/config/objects
mkdir -p ../src/config/objects
Creating directory: ../src/frontends/objects
mkdir -p ../src/frontends/objects
Creating directory: ../src/backends/objects
mkdir -p ../src/backends/objects
Creating directory: ../src/transfo/objects
mkdir -p ../src/transfo/objects
Creating directory: ../src/main/objects
mkdir -p ../src/main/objects
Creating directory: ../src/python/objects
mkdir -p ../src/python/objects
Creating directory: ../src/core/libs
mkdir -p ../src/core/libs
Creating directory: ../src/frontends/libs
mkdir -p ../src/frontends/libs
Creating directory: ../src/backends/libs
mkdir -p ../src/backends/libs
Creating directory: ../src/transfo/libs
mkdir -p ../src/transfo/libs
Creating directory: ../src/config/libs
mkdir -p ../src/config/libs
Creating directory: ../src/main/libs
mkdir -p ../src/main/libs
Creating directory: ../src/python/libs
mkdir -p ../src/python/libs
if [ -f ../tools/mknodes/mknodes.gpr ]; then \
	   mkdir -p ../tools/mknodes/objects; \
	    \
	     gnatmake -P ../tools/mknodes/mknodes.gpr \
	     -XABS_SRC_DIR="/home/anhph/ocarina-build/ocarina/src" \
	     -XABS_BUILD_DIR="/home/anhph/ocarina-build/ocarina/src" \
	     -aP../projects -aP../projects \
	     -XBUILD=release ; \
	fi
gcc-4.6 -c -gnatec=/home/anhph/ocarina-build/ocarina/src/../projects/restrictions.adc -O2 -gnat12 -gnata -gnaty -gnatyu -gnatys -gnatpn -I- -gnatA /home/anhph/ocarina-build/ocarina/tools/mknodes/mknodes.adb
/home/anhph/ocarina-build/ocarina/src/../projects/restrictions.adc:24:22: invalid restriction identifier "No_Access_Parameter_Allocators"
/home/anhph/ocarina-build/ocarina/src/../projects/restrictions.adc:25:22: invalid restriction identifier "No_Coextensions"
/home/anhph/ocarina-build/ocarina/src/../projects/restrictions.adc:30:22: invalid restriction identifier "No_Fixed_Io"
/home/anhph/ocarina-build/ocarina/src/../projects/restrictions.adc:64:22: invalid restriction identifier "No_Implicit_Task_Allocations"
/home/anhph/ocarina-build/ocarina/src/../projects/restrictions.adc:65:22: invalid restriction identifier "No_Implicit_Protected_Object_Allocations"
/home/anhph/ocarina-build/ocarina/src/../projects/restrictions.adc:75:22: invalid restriction identifier "No_Task_At_Interrupt_Priority"
/home/anhph/ocarina-build/ocarina/src/../projects/restrictions.adc:80:22: invalid restriction identifier "Pure_Barriers"
gnatmake: "/home/anhph/ocarina-build/ocarina/tools/mknodes/mknodes.adb" compilation error
make[1]: *** [build-mknodes] Error 4
make[1]: Leaving directory `/home/anhph/ocarina-build/ocarina/projects'
make: *** [all-recursive] Error 1`

Could you give some advices, please ?
Many thanks,

**Comment by yoogx** [comment]
You close it, but just in case
You may review this repository, it lists the dependencies for each distribution (review the docker file for your Linux version): https://github.com/openaadl/ocarina-docker

You need at least GNAT GPL 2016 to compile Ocarina, I see the documentation still mentions 2015, I'm correcting this
