### ISSUE TITLE
How to describe a algorithm with AADL ??

### ISSUE THREAD

**Issue by phamhoanganhbk** [OpenAADL/ocarina-build#39]
Hi everybody,

I am learning about AADL and i am running some examples of control (car control, robot control...).
But I still don't really understand how we can describe control algorithms (like PID, backstepping....) with AADL. What is the main purpose of AADL? What are the advantages while having a lot of problems with the generated code?

Could you please give me some advices?

Many thanks,
Hoang Anh

**Comment by yoogx** [comment]
Please, this is an issue tracker for bug reports. If you want some help on AADL at large, consult this
http://www.aadl.info/aadl/currentsite/ and look for the mailing lists.

Long story short: AADL is about architecture, you do not describe control algorithms. AADL concentrates on scheduling, communication, among other things. These elements are necessary to ensure that your control algorithm can be correctly implemented. For further readings, I recommend this book: https://www.amazon.com/dp/B071WHRJY3 that provides a clear view on the issues you want to tackle
