### ISSUE TITLE
Building issue

### ISSUE THREAD

**Issue by CaptainSeum** [OpenAADL/ocarina-build#42]
Hi, when I run: 

`./build_ocarina.sh --scenario=fresh-install --prefix=$PWD/ocarina_install`

I get the following logs: 

`ocarina-backends-c_common-ba.adb:2492:80: (style) this line is too long
ocarina-backends-c_common-ba.adb:2591:06: (style) incorrect layout
ocarina-backends-c_common-ba.adb:2602:03: missing "end if;" for "if" at line 2584
gnatmake: "/home/bouffies/Desktop/Ocarina/ocarina-build-2017.3/ocarina/src/backends/ocarina-backends-c_common-ba.adb" compilation error
Makefile:615: recipe for target 'ocarina-backends.gpr-build' failed
make[1]: *** [ocarina-backends.gpr-build] Error 4
make[1]: Leaving directory '/home/bouffies/Desktop/Ocarina/ocarina-build-2017.3/ocarina/projects'
Makefile:419: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

I'm trying to install ocarina on Ubuntu.

Thanks

**Comment by yoogx** [comment]
Known issue, there is a build failure caused by openaadl/ocarina#230 
It will be addressed quickly
